### ISSUE TITLE
Error: Exceeding GPU memory!

### ISSUE THREAD

**Issue by xuweidiy** [zjazz/zjazz_cuda_miner#1]
Error: Exceeding GPU memory! | Failed to create buffer (out of memory) | Requirements (1006632960) | Total memory (1006632960)
What is the problem with this? gtx1065  12 cards.

**Comment by ylpkm** [comment]
1 gpu thread takes about 3.2 gb's or so. lower your -g parameter, otherwise the card cant handle it due to not having enough memory.

**Comment by KL0nLutiy** [comment]
Hi, @zjazz, any update for gtx 1060 3 gb?

**Comment by zjazz** [comment]
3Gb are not supported yet but I'm working on it, at some point during the next week it will be ready.

**Comment by zjazz** [comment]
0.95 released, it supports 3Gb GPUs.
