### ISSUE TITLE
Mixed GPU Systems, Threads Per GPU

### ISSUE THREAD

**Issue by 9600-** [zjazz/zjazz_cuda_miner#3]
Example: 

i5-750 
2x1070 8GB
1x1060 3GB

Can execute 2 threads on the 1070s, not so on the 1060s. 
The obvious answer would be to use the device flag to run two instances, one for each GPU class, but the overhead of the second instance really takes a toll on the hash rate of the original process. 

If we could flag threads like devices, it would allow this (odd) configuration to mine at maximum efficiency. 

Example: 
"-d 0 -d 1 -d 2 -g 2 -g 2 -g 1" 

Thoughts?

**Comment by zjazz** [comment]
Thanks for your feedback., I've implemented on v0.97, released few minutes ago.

New --device-gpu-threads parameter added. Use it after selecting a device with -d, for example:

"-d 0 --device-gpu-threads 2 -d1 --device-gpu-threads 2 -d 2 --device-gpu-threads 1"
