### ISSUE TITLE
Hashrate drops 50% after reconnect

### ISSUE THREAD

**Issue by RainbowMiner** [zjazz/zjazz_cuda_miner#5]
There seems to be a problem with reconnects, if a pool stratum fails for some time.
Mining with Zjazz 1.0 on icemining.ca, I made the observation for three times now: if the stratum fails for some time, zjazz tries to reconnect until the server is back online. So far so good: but after the reconnect, the hashrate seems to be broken.
The pool reports a 50% lower hashrate and the miner window shows 1min aprox. 6% lower, 10min aprox 50% lower. It seems not to improve without restart of the miner.

**Comment by zjazz** [comment]
Thanks for reporting the issue! I've some questions about it. I saw you on discord, I'll try to catch you there (asking there will be more agile).

**Comment by RainbowMiner** [comment]
This did never happen again, since version 1.2. I close the issue.
