### ISSUE TITLE
Bugfix: Selecting a subset of gpus with -d and setting --device-gpu-threads per gpu didn't work as expected

### ISSUE THREAD

**Issue by auroracoin** [zjazz/zjazz_cuda_miner#6]
Bugfix: Selecting a subset of gpus with -d and setting --device-gpu-threads per gpu didn't work as expected.

Adding  -d 0,1  still doesn't work.  Windows 8.1   750ti  5.0
But without the -d option, it hashes both cards.

**Comment by RainbowMiner** [comment]
The comma list does not work. You need to do it like that: "-d 0 -d 1"

**Comment by auroracoin** [comment]
Ok thx :)
